job_analysis_task:
    description: >
        Analyze the provided job description and extract structured information according to the JobAnalysis model.
        Focus on ATS-compatible keywords while filtering out corporate jargon.

        **Key Instructions:**
        - Extract concrete skills, tools, technologies, qualifications, responsibilities, duties, and company culture keywords
        - Ignore corporate jargon and buzzwords like "rockstar," "ninja," "synergy," "disruptive," "game-changer"
        - Focus on specific technical skills, programming languages, tools, certifications and leadership/management skills
        - Capture actual responsibilities and duties, not generic corporate speak
        - Extract company mission/values that are substantive, not just marketing fluff
        - Standardize the job title to its core functional role. Remove all seniority levels, qualifiers, and program-specific tags.
        - Strip out all terms like "1", "2", "I", "II", "Associate", "Senior" and tags like "Early Careers", "New Grad", etc from the job title.
        - Standardize the location to the format 'City, ST, USA'.

        **Extract the following structured data:**

        **1. Job Details (job_details):**
        - company_name: The name of the hiring company
        - job_title: The standardized job title (core functional role only)
        - location: Location in 'City, ST, USA' format
        - job_id: Job identifier if available (optional)

        **2. Skills (skills):**
        - technical: List of technical, hard, tools, and technologies (Python, SQL, GCP, AWS, Tableau, Power BI, Looker, etc.)
        - soft: List of soft or interpersonal skills (communication, teamwork, etc.)
        - management: List of management or leadership skills (cross-functional collaboration, stakeholder management, etc.)
        - bonus: List of skills mentioned as 'plus' or 'nice-to-have'

        **3. Key Terms (key_terms):**
        - responsibilities_and_qualifications: Verbatim list of responsibilities and qualifications from the job description
        - company_culture_keywords: Keywords related to the company's mission, culture, and values

        Job Description:
        ```
        {job_description}
        ```

    expected_output: >
        A clean JSON object following the `JobAnalysis` Pydantic model structure with three main sections:
        - job_details: Core job and company information
        - skills: Categorized breakdown of all required skills (technical, soft, management, bonus)
        - key_terms: Categorized breakdown of responsibilities/qualifications and company culture keywords

        Focus on extracting concrete, ATS-friendly keywords while filtering out meaningless corporate jargon.
        Do not include any preamble or extra text outside of the JSON object.

resume_tailoring_task:
    description: >
        Using the master resume and the job analysis report, rewrite the resume to be perfectly tailored for the target role.
        Follow all guidelines meticulously.

        **General Guidelines:**
        1. **Natural Keyword Integration:**:
            - Strategically integrate keywords from the job analysis report throughout the resume in a natural, contextual manner.
            - Keywords should flow seamlessly within accomplishment statements and descriptions.
            - Focus on relevance and natural placement where they add genuine value.
            - Distribute keywords strategically across sections to avoid concentration in any single area.
            
        2. **ATS Optimization with Human Readability:**
            - Mirror the exact language from responsibilities_and_qualifications in the job analysis to maximize ATS matching.
            - Each responsibility/qualification from the job analysis should be reflected AT MOST ONCE across the entire resume.
            - Track which responsibilities/qualifications you've already incorporated to avoid duplication.
            - Balance ATS optimization with compelling human-readable content.
            
        3. **Keyword Distribution Strategy:**
            - Avoid keyword stuffing by using each critical keyword 1-3 times maximum across the entire resume.
            - Prioritize keyword placement in order: Professional Summary > Most Recent Role > Projects > Earlier Roles.
            - Use variations and synonyms where appropriate to demonstrate depth without repetition.
            - Never force keywords where they don't naturally fit the context.
            
        4. **Language:**
            - Avoid filler or corporate buzzwords (e.g., synergy, go-getter, visionary).
            - Use precise, action-oriented language tied to measurable outcomes.
            
        5. **Authenticity:**
            - Only use experiences, achievements, and skills present in the master resume.
            - You may rephrase or highlight content but must not fabricate information.
            
        6. **Scope**:
            - Modify only the following sections: Professional Summary, Work Experience, Education, Projects, Skills.
            - Do not add extra sections.

        **Section-Specific Guidelines:**

        **A) Professional Summary:**
        1. Write a compelling summary between 70-100 words.
        2. Begin with the job title from the job analysis, followed by the candidate's years of experience.
        3. Highlight 1-2 core areas of expertise that directly align with the job's primary responsibilities.
        4. Mirror 2-3 high-priority responsibilities/qualifications from the job analysis using exact or very similar phrasing.
        5. Conclude with a significant, quantified achievement that showcases proficiency with a key tool or technology mentioned in the analysis.
        6. Mention key tools, technologies, or skills from the job analysis in a natural way.
        7. Use a tone aligned with the job responsibilities (e.g., collaborative, innovative, detail-oriented).
        8. If company mission/values are present in the job analysis, use them to express your commitment to staying up-to-date with the industry.
        9. Do not mention the company name in the summary.
        10. Track which responsibilities/qualifications you use here to avoid repeating them elsewhere.

        **B) Work Experience:**
        1. Update the title of the most recent role to match the job title from the job analysis. Do not change earlier roles.
        2. For each role, select the 5 most relevant bullet points from the master resume that directly and/or indirectly align with the responsibilities in the job analysis.
        3. Rewrite each bullet point in the result-oriented format:
            - Accomplished [X] by doing [Z], resulting in [Y].
            - Each bullet should mirror ONE unique responsibility/qualification from the job analysis that hasn't been used elsewhere.
            - Incorporate the exact phrasing or very close variations of responsibilities/qualifications.
            - Incorporate a quantifiable metric (e.g., percentages, dollar amounts, time saved) where possible to demonstrate tangible results.
        4. Begin each bullet with a unique, strong action verb. Do not repeat verbs within the same role.
        5. Distribute different responsibilities/qualifications across roles - don't concentrate all matching in one position.
        6. For the most recent role, prioritize the most critical responsibilities from the job analysis.
        7. For earlier roles, use complementary responsibilities that support but don't duplicate the recent role's focus.
        8. Ensure bullet points directly reflect responsibilities and duties from the job analysis without over-repetition.

        **C) Education:**
        1. For each degree, list up to 5 relevant courses.
        2. Select only courses that are directly related to keywords, skills, or responsibilities from the job analysis.
        3. Course names can subtly reinforce keywords without duplicating exact responsibility phrases used elsewhere.
        4. Do not list unrelated or filler coursework.

        **D) Projects:**
        1. For each project, expand the description to include:
            - Goal/Purpose of the project aligned with responsibilities not yet covered in work experience.
            - Technologies/Tools used (prioritize those from the job analysis not heavily featured elsewhere).
            - Impact or outcome that demonstrates competency in a unique responsibility/qualification.
        2. Keep each description under 3 sentences.
        3. Use projects to cover any remaining high-priority responsibilities/qualifications not addressed in other sections.
        4. Emphasize alignment with the target job's duties and responsibilities using varied language.

        **E) Skills:**
        1. Include only technical/hard skills and methodologies (e.g., Programming Languages, Frameworks, Databases, Tools, SDLC, TDD, Agile).
        2. Retain all existing technical skills from the master resume.
        3. Remove soft skills (e.g., communication, teamwork, leadership) if present.
        4. Add technical skills from the job analysis where relevant.
        5. This section should comprehensively list all technical keywords without narrative repetition.
        6. Organize skills under clear categories, for example:
            - Programming Languages
            - Frameworks and Libraries
            - Databases
            - Tools and Platforms
            - Methodologies

        **Content Integration Marking:**
        - Mark ALL integrated content from the job analysis in **markdown bold** format.
        - This includes: responsibilities, qualifications, skills, tools, technologies, and company culture keywords.
        - Use **bold** to highlight exact phrases or close variations that come from the job analysis.

        **Quality Check Before Finalizing:**
        - Verify each responsibility/qualification from the job analysis appears at most once across all sections.
        - Ensure critical keywords appear 1-3 times maximum throughout the resume.
        - Confirm the resume reads naturally to a human while containing ATS-friendly keywords.
        - Check that keyword placement feels organic and adds value to the content.
        - Verify that all integrated content from the job analysis is properly marked in **bold**.

        **Master Resume:**
        ```json
        {master_resume}
    expected_output: >
        A single, clean JSON object that strictly adheres to the `Resume` Pydantic model.
        Do not include any introductory text, explanations, or any content outside of the final JSON object.

resume_refinement_task:
    description: >
        Review and refine the tailored resume to ensure it sounds authentically human while 
        maintaining ATS optimization. Apply all refinement guidelines to create a polished, 
        professional document that balances keyword optimization with natural readability.

        **Core Refinement Guidelines:**

        **1. Length Constraints (STRICT):**
        - Professional Summary: Maximum 100 words (count every word)
        - Bullet Points: 15-25 words each (strictly enforced)
        - If content exceeds limits, prioritize impact and cut filler

        **2. Preserve Critical Elements:**
        - NEVER modify or remove **bold formatted** keywords/phrases
        - These bolded terms are ATS-critical and must remain exactly as marked
        - You may rewrite around them but the bold text itself stays unchanged

        **3. Language Naturalization:**
        - Eliminate AI patterns: "leveraged", "spearheaded", "utilizing", "furthermore"
        - Remove redundant phrases: "successfully completed" → "completed"
        - Cut unnecessary adverbs: "effectively managed" → "managed"
        - Replace generic terms with industry-specific language
        - Vary sentence beginnings (not every bullet starts with past-tense verb)

        **4. Active Voice Transformation:**
        - Identify all passive constructions and rewrite with strong action verbs
        - Examples:
          * "Was responsible for..." → "Managed..."
          * "Tasks were completed..." → "Completed tasks..."
          * "Improvements were implemented..." → "Implemented improvements..."

        **5. Quantifiable Impact Refinement:**
        - Limit to 1-2 metrics per bullet point (remove excess numbers)
        - Professional Summary: Maximum 1 quantified achievement
        - Choose the most impressive metric when multiple exist
        - Format consistently: Use % for percentages, K/M for thousands/millions

        **6. Sentence Structure Variation:**
        - Mix short (10-15 words) and longer (20-25 words) bullet points
        - Occasionally start with results: "Reduced costs 30% by..."
        - Use participial phrases sparingly: "Working with cross-functional teams..."
        - Include time-based achievements: "In 6 months, achieved..."

        **7. Human Voice Techniques:**
        - Add transitional phrases that humans use: "Additionally", "As a result"
        - Include industry colloquialisms where appropriate
        - Use contractions sparingly in less formal contexts
        - Vary verb tenses appropriately (past for previous roles, present for current)

        **8. Consistency Checks:**
        - Formatting: Ensure uniform bullet point style (periods or no periods)
        - Capitalization: Consistent approach to job titles, technologies
        - Punctuation: Check for Oxford commas, semicolon usage
        - Date formats: Ensure all dates follow same pattern (MM/YYYY or Month YYYY)

        **9. Flow and Readability:**
        - Read each section aloud to catch awkward phrasing
        - Ensure smooth transitions between bullet points
        - Create narrative coherence within each role
        - Avoid starting consecutive bullets with the same word

        **10. Final Polish:**
        - Remove all instances of corporate buzzwords: synergy, leverage, utilize
        - Eliminate redundant qualifiers: "very", "extremely", "highly"
        - Check spelling and grammar meticulously
        - Ensure industry terms are used correctly and naturally

        **Section-Specific Refinement:**

        **Professional Summary:**
        - First sentence: Role + years of experience (natural phrasing)
        - Middle: 2-3 key strengths written conversationally
        - Last sentence: One impressive achievement with metric
        - Total word count: 70-100 words maximum
        - Write as a cohesive paragraph, not disconnected statements

        **Work Experience:**
        - Vary bullet point lengths within the 15-25 word range
        - Create logical flow from strategic to tactical achievements
        - Use different action verbs for each bullet (no repetition within role)
        - Include context where needed: "During peak season, managed..."
        - Balance technical achievements with business impact

        **Projects:**
        - Write in narrative style, not bullet points
        - Focus on problem-solution-result structure
        - Keep descriptions conversational yet professional
        - Maximum 3 sentences per project

        **Education:**
        - List courses naturally: "Relevant coursework includes..."
        - Use course names that sound academic, not keyword-stuffed

        **Skills:**
        - Organize logically with clear categories
        - Use industry-standard names for technologies
        - Avoid redundancy (don't list Python and Python 3.x)

        **Quality Assurance Checklist:**
        - All bullet points between 15-25 words
        - Professional summary under 100 words
        - No passive voice constructions
        - Bold formatting preserved exactly
        - Maximum 2 metrics per bullet point
        - No repeated action verbs within sections
        - Varied sentence structures
        - No AI-pattern words or corporate jargon
        - Natural, human-sounding language throughout
        - Consistent formatting and punctuation

    expected_output: >
        A refined JSON resume following the exact Resume model structure that:
        - Sounds genuinely human-written with natural language flow
        - Maintains all **bold** keyword formatting without modification
        - Adheres strictly to word count limits (summary ≤100 words, bullets 15-25 words)
        - Contains no passive voice, AI patterns, or corporate jargon
        - Features varied sentence structures and industry-authentic language
        - Includes 1-2 quantifiable metrics per bullet point maximum
        - Demonstrates perfect consistency in formatting and style
        - Reads smoothly when spoken aloud

        Output only the refined JSON object with no additional text or explanation.
