job_analysis_task:
    description: >
        Analyze the provided job description and extract structured information according to the JobAnalysis model.
        Focus on ATS-compatible keywords while systematically filtering out corporate jargon and buzzwords.

        **Key Instructions:**
        - Extract concrete skills, tools, technologies, qualifications, responsibilities, and duties
        - Aggressively filter out corporate jargon like "rockstar," "ninja," "synergy," "disruptive," "game-changer," "dynamic," "fast-paced," "world-class", "problem solving"
        - Focus on specific technical skills, programming languages, tools, certifications, and measurable leadership/management skills
        - Distill responsibilities and qualifications into their core, actionable essence—remove fluff and rewrite in clear, direct language
        - Extract only substantive company mission/values keywords, not generic marketing phrases

        Job Description:
        ```
        {job_description}
        ```

    expected_output: >
        A clean JSON object following the `JobAnalysis` Pydantic model structure.
        Focus on extracting concrete, ATS-friendly keywords while filtering out meaningless corporate jargon.
        Do not include any preamble or extra text outside of the JSON object.

resume_tailoring_task:
    description: >
        Using the master resume and job analysis, strategically rewrite the resume to authentically align
        with the target role. Create a polished, human-readable document that naturally integrates keywords
        without sounding robotic or AI-generated.

        **Core Principles:**

        **AUTHENTICITY (NON-NEGOTIABLE):**
        - NEVER add any skill, experience, tool, technology, or qualification not explicitly present in the master resume.
        - You may rephrase, emphasize, or contextualize existing content, but fabrication is strictly forbidden.
        - When aligning with job requirements, adapt the candidate's genuine experience using relevant keywords—do not invent capabilities.

        **LANGUAGE & TONE:**
        - Write the entire resume in third person. Do NOT use first-person pronouns like "I," "me," or "my."
        - Use precise, action-oriented language. Avoid AI patterns ("leveraged," "spearheaded," "utilizing") and corporate buzzwords (synergy, go-getter, disruptive).
        - Eliminate passive voice. Use strong, varied action verbs.
        - Vary sentence structures naturally—mix sentence lengths and starting patterns to avoid formulaic repetition.
        - Write content that sounds genuinely human, as if crafted by a thoughtful professional, not generated by AI.

        **KEYWORD INTEGRATION:**
        - Strategically weave keywords from the job analysis throughout the resume where they authentically fit the candidate's experience.
        - Prioritize keyword placement: Professional Summary > Most Recent Role > Projects > Earlier Roles > Education.
        - Use each critical keyword 1-3 times maximum across the entire resume to avoid stuffing.
        - Never force keywords where they don't naturally align with the candidate's actual work.

        **Length Constraints:**
        - Professional Summary: 70-100 words maximum
        - Work Experience bullets: 15-25 words each
        - Project descriptions: Maximum 3 sentences each

        **Section Guidelines:**

        **Professional Summary (70-100 words):**
        Write a concise, compelling 3-4 sentence summary that positions the candidate for this specific role.
        Start with the target job title and years of experience, highlight 2-3 areas of expertise aligned
        with key job responsibilities, and conclude with a quantified achievement demonstrating relevant technical
        proficiency. Naturally integrate high-priority keywords from the job analysis. Write as a cohesive,
        conversational paragraph. Do not mention the company name.

        **Work Experience:**
        - Update the most recent role's title to match the job analysis. Keep earlier titles unchanged.
        - Select the 5 most relevant accomplishments from each role in the master resume.
        - Rewrite bullets (15-25 words each) using STAR method principles: clearly state the action taken and the quantifiable result or impact.
        - Use strong, varied action verbs (no repetition within a role).
        - Include 1-2 metrics per bullet maximum. Format consistently (% for percentages, K/M for thousands/millions).
        - Vary bullet structures—occasionally start with results ("Reduced costs 30% by..."), use time-based achievements ("In 6 months, achieved...").
        - Distribute keyword integration across roles—prioritize critical responsibilities in the most recent position.

        **Education:**
        List up to 5 relevant courses per degree that directly relate to skills or responsibilities from the job analysis.
        Use natural phrasing ("Relevant coursework includes..."). Omit unrelated coursework.

        **Projects:**
        Expand project descriptions (max 3 sentences each) in narrative style to highlight purpose, relevant technologies
        from the job analysis, and measurable outcomes. Use projects to demonstrate competencies not fully covered in work
        experience. Write conversationally, using problem-solution-result structure.

        **Skills:**
        - List only technical/hard skills and methodologies (no soft skills like "communication" or "teamwork").
        - Retain all existing technical skills from the master resume.
        - Organize into clear categories (Programming Languages, Frameworks, Databases, Tools, Methodologies).
        - Use industry-standard names. Avoid redundancy (don't list "Python" and "Python 3.x").
        - DO NOT add technical skills from the job analysis unless they are genuinely implied or demonstrated by existing project/work experience in the master resume.

        **Master Resume:**
        ```json
        {master_resume}
    expected_output: >
        A single, clean JSON object that strictly adheres to the `Resume` Pydantic model.
        Do not include any introductory text, explanations, or any content outside of the final JSON object.

