job_analysis_task:
    description: >
        Analyze the job description and extract all skills, requirements, and company signals for ATS optimization.

        Job Description:
        ```
        {job_description}
        ```

        **Extract and categorize:**

        Skills - Separate into technical (programming languages, tools, platforms, certifications), soft (communication, problem-solving),
        management (leadership, stakeholder management, strategic planning), and bonus/nice-to-have qualifications.
        Use exact terminology including abbreviations and version numbers.

        Responsibilities & Qualifications - Extract complete phrases covering duties, requirements, and qualifications.
        Strip buzzwords like "rockstar," "synergy," "disruptive" but preserve core meaning and industry-specific terminology.
        Include quantifiable requirements (years of experience, education). Flag repeated or emphasized phrases as high priority.

        Company Signals - Identify tone/priorities (fast-paced, collaborative, data-driven, innovative) and cultural values
        (diversity, growth mindset, work-life balance, mission alignment). Exclude generic marketing language.

        **Quality standards:**
        - Comprehensive: capture every substantive skill and requirement
        - Precise: use exact terminology from job description
        - Deduplicated: each item appears once across all categories
        - Actionable: focus on concrete, verifiable qualifications over vague attributes

    expected_output: >
        Complete JobAnalysis object with categorized extraction. No preamble or explanatory text.

resume_tailoring_task:
    description: >
        Using the master resume and job analysis, strategically rewrite the resume to authentically align
        with the target role. Create a polished, human-readable document that naturally integrates keywords
        without sounding robotic or AI-generated.

        **Core Principles:**

        **AUTHENTICITY (NON-NEGOTIABLE):**
        - NEVER add any skill, experience, tool, technology, or qualification not explicitly present in the master resume.
        - You may rephrase, emphasize, or contextualize existing content, but fabrication is strictly forbidden.
        - When aligning with job requirements, adapt the candidate's genuine experience using relevant keywords—do not invent capabilities.

        **LANGUAGE & TONE:**
        - Write the entire resume in third person. Do NOT use first-person pronouns like "I," "me," or "my."
        - Use precise, action-oriented language. Avoid AI patterns ("leveraged," "spearheaded," "utilizing") and corporate buzzwords (synergy, go-getter, disruptive).
        - Eliminate passive voice. Use strong, varied action verbs.
        - Vary sentence structures naturally—mix sentence lengths and starting patterns to avoid formulaic repetition.
        - Write content that sounds genuinely human, as if crafted by a thoughtful professional, not generated by AI.

        **KEYWORD INTEGRATION:**
        - Strategically weave keywords from the job analysis throughout the resume where they authentically fit the candidate's experience.
        - Prioritize keyword placement: Professional Summary > Most Recent Role > Projects > Earlier Roles > Education.
        - Use each critical keyword 1-3 times maximum across the entire resume to avoid stuffing.
        - Never force keywords where they don't naturally align with the candidate's actual work.

        **Length Constraints:**
        - Professional Summary: 70-100 words maximum
        - Work Experience bullets: 15-25 words each
        - Project descriptions: Maximum 3 sentences each

        **Section Guidelines:**

        **Professional Summary (70-100 words):**
        Write a concise, compelling 3-4 sentence summary that positions the candidate for this specific role.
        Start with the target job title and years of experience, highlight 2-3 areas of expertise aligned
        with key job responsibilities, and conclude with a quantified achievement demonstrating relevant technical
        proficiency. Naturally integrate high-priority keywords from the job analysis. Write as a cohesive,
        conversational paragraph. Do not mention the company name.

        **Work Experience:**
        - Update the most recent role's title to match the job analysis. Keep earlier titles unchanged.
        - Select the 5 most relevant accomplishments from each role in the master resume.
        - Rewrite bullets (15-25 words each) using STAR method principles: clearly state the action taken and the quantifiable result or impact.
        - Use strong, varied action verbs (no repetition within a role).
        - Include 1-2 metrics per bullet maximum. Format consistently (% for percentages, K/M for thousands/millions).
        - Vary bullet structures—occasionally start with results ("Reduced costs 30% by..."), use time-based achievements ("In 6 months, achieved...").
        - Distribute keyword integration across roles—prioritize critical responsibilities in the most recent position.

        **Education:**
        List up to 5 relevant courses per degree that directly relate to skills or responsibilities from the job analysis.
        Use natural phrasing ("Relevant coursework includes..."). Omit unrelated coursework.

        **Projects:**
        Expand project descriptions (max 3 sentences each) in narrative style to highlight purpose, relevant technologies
        from the job analysis, and measurable outcomes. Use projects to demonstrate competencies not fully covered in work
        experience. Write conversationally, using problem-solution-result structure.

        **Skills:**
        - List only technical/hard skills and methodologies (no soft skills like "communication" or "teamwork").
        - Retain all existing technical skills from the master resume.
        - Organize into clear categories (Programming Languages, Frameworks, Databases, Tools, Methodologies).
        - Use industry-standard names. Avoid redundancy (don't list "Python" and "Python 3.x").
        - DO NOT add technical skills from the job analysis unless they are genuinely implied or demonstrated by existing project/work experience in the master resume.

        **Master Resume:**
        ```json
        {master_resume}
    expected_output: >
        A single, clean JSON object that strictly adheres to the `Resume` Pydantic model.
        Do not include any introductory text, explanations, or any content outside of the final JSON object.

resume_validation_task:
    description: >
        Validate the tailored resume against the job analysis to ensure quality, keyword integration,
        and readiness for document generation. Use the context from previous tasks (job analysis and
        tailored resume) to perform comprehensive analysis and provide actionable feedback.

        **Validation Criteria:**

        **1. Keyword Integration Analysis:**
        - Count total keywords from job analysis (technical skills, soft skills, management skills, and key terms)
        - Identify which keywords appear in the resume
        - Calculate integration rate (percentage of keywords included)
        - Classify keywords as naturally integrated vs. forced/awkwardly placed
        - Identify missing critical keywords that should be added
        - Check for keyword stuffing (same keyword repeated excessively)

        **2. Phrase Usage Analysis:**
        - Verify that responsibilities and qualifications from job analysis are reflected in resume
        - Check if industry-specific terminology is used correctly and in proper context
        - Identify phrases that sound unnatural or AI-generated ("leveraged," "spearheaded," "synergy")
        - Note important phrases from job description that should be incorporated

        **3. ATS Compatibility Check:**
        - Evaluate keyword density and distribution across resume sections
        - Verify technical skills are explicitly stated (not just implied)
        - Check if quantifiable achievements are present
        - Assess overall structure and formatting compatibility
        - Score from 0-100 based on ATS optimization

        **4. Human Readability Assessment:**
        - Evaluate natural language flow and sentence variety
        - Identify robotic patterns or AI-generated phrases
        - Check for authentic voice and third-person consistency
        - Assess if experience sounds genuine vs. fabricated
        - Score from 0-100 based on human readability

        **5. Quality Feedback:**
        - List 3-5 specific strengths of the resume
        - List 3-5 weaknesses or areas for improvement
        - Provide 3-5 actionable suggestions for enhancement
        - Calculate overall score (weighted: 40% keyword integration, 30% ATS score, 30% readability)

        **6. Pass/Fail Determination:**
        - Resume passes if: overall score >= 75, ATS score >= 70, readability score >= 70, integration rate >= 60%
        - Resume is ready for generation if: passed_validation = True AND no critical keywords missing

        **Note:** Do NOT use the document generation tool. The validation report will be used by the main
        workflow to generate the document. Focus only on validation and providing the comprehensive report.

    expected_output: >
        A comprehensive ResumeValidationReport JSON object that includes all analysis, scores, feedback,
        and pass/fail determination based on the job analysis and tailored resume from previous tasks.
        Do not include any preamble or extra text outside of the JSON object.
